env:
  global:
    - REPO_DIR=.
    - BUILD_COMMIT=$TRAVIS_COMMIT
    - PLAT=x86_64

install: 
  - git clone https://github.com/prakritichauhanpuresoftware/multibuild
  - . multibuild/common_utils.sh
  - . multibuild/travis_steps.sh
  - before_install 
  # - clean_code $REPO_DIR $BUILD_COMMIT
  - build_wheel $REPO_DIR $PLAT
script: 
  - install_run $PLAT

after_success:
  - ./deploy.sh

    
matrix:
  include:

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
 
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7

    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
    
    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
 
    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8

    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.9
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8

    - os: osx
      osx_image: xcode8.3
      env:
        - MB_PYTHON_VERSION=3.5
        - DEPLOY_SDIST=true
 
    - os: osx
      osx_image: xcode8.3
      env:
        - MB_PYTHON_VERSION=3.6
 
    - os: osx
      osx_image: xcode8.3
      env:
        - MB_PYTHON_VERSION=3.7
 
 
